// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./navMenu";
import { Quicksand } from 'next/font/google'

const quick_font= Quicksand ({
  subsets: ['latin'],
  variable: '--font-quicksand',
  display: 'swap',
})
// export const metadata = {
//   icons: {
//     icon: '/favicon.ico', // /public path
    
//   },
// }
// export const metadata: Metadata = {
//   // title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
 children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" className={`${quick_font.variable}`}>
      <body>
       <NavBar/>
        {children}
      </body>
    </html>
    </>
    
  );
}
